[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "spatialbench-cli"
dynamic = ["version"]
description = "Python CLI for Spatial Bench data generator"
requires-python = ">=3.8"

[tool.maturin]
bindings = "bin"  # this makes maturin treat it as a binary crate (not a library)
